version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  pokerino.server:
    image: ${DOCKER_REGISTRY-}pokerino
    depends_on:
       - "pokerino.db"
    build:
      context: .
      dockerfile: Server/Dockerfile
    networks:
      - dev

  pokerino.db:
    image: postgres:latest
    container_name: pokerino.db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=martinpetr
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pokerino_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  pokerino_data: